env:
  browser: true
  commonjs: true
  jest/globals: true
extends:
  - plugin:react-hooks/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
parser: "@typescript-eslint/parser"
parserOptions: 
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: 'module'
plugins:
  - "@typescript-eslint"
  - jest
rules:
  'prettier/prettier': ['error', {endOfLine: 'auto'}]
  react-hooks/rules-of-hooks:  "error"
  react-hooks/exhaustive-deps: "warn"
  react/react-in-jsx-scope: 0
  react/prop-types: 0
  no-console: "error"
  no-shadow: off
  "@typescript-eslint/no-shadow":
    - error
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define":
    - error
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .tsx

settings:
  react:
    pragma: React
